rvm: 2.7.2
cache: bundler

import:
  - travis-ci/build-configs:db-setup.yml

services:
  - redis

before_install:
  - gem uninstall -v '>=2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.17.3'

env:
  global:
    - PATH=/snap/bin:$PATH

jobs:
  include:
    - stage: "testing time"
      script: bundle exec rspec